name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # <-- Este paso es obligatorio

    - name: Set up Python virtual environment
      run: |
        python3 -m venv .venv
        source .venv/bin/activate
        pip install -r requirements.txt
